In [1]:
import pandas as pd
import numpy as np

In [11]:
df= pd.read_csv("student.csv")
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [15]:
df.columns

Index(['roll', 'name', 'class', 'marks', 'age'], dtype='object')

In [13]:
df.shape

(10, 5)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   roll    10 non-null     int64
 1   name    10 non-null     object
 2   class   10 non-null     object
 3   marks   10 non-null     float64
 4   age     10 non-null     int64
dtypes: float64(1), int64(2), object(2)
memory usage: 532.0+ bytes

In [14]:
df.dtypes

roll       int64
name      object
class     object
marks    float64
age        int64
dtype: object

In [22]:
df.head()# by default it will show first 5 data of file

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20

In [23]:
df.head(7)

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19

In [24]:
df.tail()# By default it will show ending 5 rows

   roll    name class  marks  age
5     6  ayesha    BE  49.55   20
6     7    amar    BE  65.34   19
7     8   amita    BE  68.33   23
8     9    amol    TE  56.75   20
9    10   anmol    BE  78.66   21

In [25]:
df.tail(7)

   roll     name class  marks  age
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [26]:
df.values

array([[1, 'anil', 'TE', 56.77, 22],
       [2, 'amit', 'TE', 59.77, 21],
       [3, 'aniket', 'BE', 76.88, 19],
       [4, 'ajinkya', 'TE', 69.66, 20],
       [5, 'asha', 'TE', 63.28, 20],
       [6, 'ayesha', 'BE', 49.55, 20],
       [7, 'amar', 'BE', 65.34, 19],
       [8, 'amita', 'BE', 68.33, 23],
       [9, 'amol', 'TE', 56.75, 20],
       [10, 'anmol', 'BE', 78.66, 21]], dtype=object)

In [27]:
df.T# the colum becomes rows and rows become column by transpose

,0,1,2,3,4,5,6,7,8,9
roll,1,2,3,4,5,6,7,8,9,10
name,anil,amit,aniket,ajinkya,asha,ayesha,amar,amita,amol,anmol
class,TE,TE,BE,TE,TE,BE,BE,BE,TE,BE
marks,56.77,59.77,76.88,69.66,63.28,49.55,65.34,68.33,56.75,78.66
age,22,21,19,20,20,20,19,23,20,21

In [28]:
# Slicing 
''''
Panadas give two type of option for slicing one is index based and other is column based
for index based we use iloc method
an for column based we use

In [29]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [32]:
df[1:4]

   roll     name class  marks  age
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20

In [34]:
df.iloc[1:4]

   roll     name class  marks  age
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20

In [36]:
df.iloc[1:4,1:4]# corrrect one we choice 1 row till 4 and same for other we start from 1 row  till 4 column

      name class  marks
1     amit    TE  59.77
2   aniket    BE  76.88
3  ajinkya    TE  69.66

In [38]:
help(df.iloc())

Help on _iLocIndexer in module pandas.core.indexing object:

class _iLocIndexer(_LocationIndexer)
 |  Purely integer-location based indexing for selection by position.
 |
 |  .. deprecated:: 2.2.0
 |
 |     Returning a tuple from a callable is deprecated.
 |
 |  ``.iloc[]`` is primarily integer position based (from ``0`` to
 |  ``length-1`` of the axis), but may also be used with a boolean
 |  array.
 |
 |  Allowed inputs are:
 |
 |  - An integer, e.g. ``5``.
 |  - A list or array of integers, e.g. ``[4, 3, 0]``.
 |  - A slice object with ints, e.g. ``1:7``.
 |  - A boolean array.
 |  - A ``callable`` function with one argument (the calling Series or
 |    DataFrame) and that returns valid output for indexing (one of the above).
 |    This is useful in method chains, when you don't have a reference to the
 |    calling object, but would like to base your selection on
 |    some value.
 |  - A tuple of row and column indexes. The tuple elements consist of one of the
 |    above inputs, e.g. ``(0, 1)``.
 |
 |  ``.iloc`` will raise ``IndexError`` if a requested indexer is
 |  out-of-bounds, except *slice* indexers which allow out-of-bounds
 |  indexing (this conforms with python/numpy *slice* semantics).
 |
 |  See more at :ref:`Selection by Position <indexing.integer>`.
 |
 |  See Also
 |  --------
 |  DataFrame.iat : Fast integer location scalar accessor.
 |  DataFrame.loc : Purely label-location based indexer for selection by label.
 |  Series.iloc : Purely integer-location based indexing for
 |                 selection by position.
 |
 |  Examples
 |  --------
 |  >>> mydict = [{'a': 1, 'b': 2, 'c': 3, 'd': 4},
 |  ...           {'a': 100, 'b': 200, 'c': 300, 'd': 400},
 |  ...           {'a': 1000, 'b': 2000, 'c': 3000, 'd': 4000}]
 |  >>> df = pd.DataFrame(mydict)
 |  >>> df
 |        a     b     c     d
 |  0     1     2     3     4
 |  1   100   200   300   400
 |  2  1000  2000  3000  4000
 |
 |  **Indexing just the rows**
 |
 |  With a scalar integer.
 |
 |  >>> type(df.iloc[0])
 |  <class 'pandas.core.series.Series'>
 |  >>> df.iloc[0]
 |  a    1
 |  b    2
 |  c    3
 |  d    4
 |  Name: 0, dtype: int64
 |
 |  With a list of integers.
 |
 |  >>> df.iloc[[0]]
 |     a  b  c  d
 |  0  1  2  3  4
 |  >>> type(df.iloc[[0]])
 |  <class 'pandas.core.frame.DataFrame'>
 |
 |  >>> df.iloc[[0, 1]]
 |       a    b    c    d
 |  0    1    2    3    4
 |  1  100  200  300  400
 |
 |  With a `slice` object.
 |
 |  >>> df.iloc[:3]
 |        a     b     c     d
 |  0     1     2     3     4
 |  1   100   200   300   400
 |  2  1000  2000  3000  4000
 |
 |  With a boolean mask the same length as the index.
 |
 |  >>> df.iloc[[True, False, True]]
 |        a     b     c     d
 |  0     1     2     3     4
 |  2  1000  2000  3000  4000
 |
 |  With a callable, useful in method chains. The `x` passed
 |  to the ``lambda`` is the DataFrame being sliced. This selects
 |  the rows whose index label even.
 |
 |  >>> df.iloc[lambda x: x.index % 2 == 0]
 |        a     b     c     d
 |  0     1     2     3     4
 |  2  1000  2000  3000  4000
 |
 |  **Indexing both axes**
 |
 |  You can mix the indexer types for the index and columns. Use ``:`` to
 |  select the entire axis.
 |
 |  With scalar integers.
 |
 |  >>> df.iloc[0, 1]
 |  2
 |
 |  With lists of integers.
 |
 |  >>> df.iloc[[0, 2], [1, 3]]
 |        b     d
 |  0     2     4
 |  2  2000  4000
 |
 |  With `slice` objects.
 |
 |  >>> df.iloc[1:3, 0:3]
 |        a     b     c
 |  1   100   200   300
 |  2  1000  2000  3000
 |
 |  With a boolean array whose length matches the columns.
 |
 |  >>> df.iloc[:, [True, False, True, False]]
 |        a     c
 |  0     1     3
 |  1   100   300
 |  2  1000  3000
 |
 |  With a callable function that expects the Series or DataFrame.
 |
 |  >>> df.iloc[:, lambda df: [0, 2]]
 |        a     c
 |  0     1     3
 |  1   100   300
 |  2  1000  3000
 |
 |  Method resolution order:
 |      _iLocIndexer
 |      _LocationIndexer
 |      pandas._libs.indexing.NDFrameIndexerBase
 |      builtins.object
 |
 |  Data and other attributes defined here:
 |
 |  __annotations__ = {}
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from _LocationIndexer:
 |
 |  __call__(self, axis: 'Axis | None' = None) -> 'Self'
 |      Call self as a function.
 |
 |  __getitem__(self, key)
 |
 |  __setitem__(self, key, value) -> 'None'
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from _LocationIndexer:
 |
 |  __dict__
 |      dictionary for instance variables
 |
 |  __weakref__
 |      list of weak references to the object
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes inherited from _LocationIndexer:
 |
 |  axis = None
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from pandas._libs.indexing.NDFrameIndexerBase:
 |
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  __reduce__ = __reduce_cython__(...)
 |
 |  __reduce_cython__(self)
 |
 |  __setstate__ = __setstate_cython__(...)
 |
 |  __setstate_cython__(self, __pyx_state)
 |
 |  ----------------------------------------------------------------------
 |  Static methods inherited from pandas._libs.indexing.NDFrameIndexerBase:
 |
 |  __new__(*args, **kwargs) class method of pandas._libs.indexing.NDFrameIndexerBase
 |      Create and return a new object.  See help(type) for accurate signature.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from pandas._libs.indexing.NDFrameIndexerBase:
 |
 |  name
 |
 |  ndim
 |
 |  obj

# First parameters are for rows and another one is for column for accessing

In [56]:
df.iloc[1:5,[0,1,3]]

   roll     name  marks
1     2     amit  59.77
2     3   aniket  76.88
3     4  ajinkya  69.66
4     5     asha  63.28

In [71]:
df.iloc[[1,2,3,4,7],[0,1,3]]

   roll     name  marks
1     2     amit  59.77
2     3   aniket  76.88
3     4  ajinkya  69.66
4     5     asha  63.28
7     8    amita  68.33

In [69]:
df.iloc[5,1]="geet"
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6     geet    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [72]:
#loc

In [76]:
df.loc[2:5,['name','class']]

      name class
2   aniket    BE
3  ajinkya    TE
4     asha    TE
5     geet    BE

In [79]:
df.loc[0:9,['name']]

      name
0     anil
1     amit
2   aniket
3  ajinkya
4     asha
5     geet
6     amar
7    amita
8     amol
9    anmol

In [81]:
df.loc[0:9,'name']

0       anil
1       amit
2     aniket
3    ajinkya
4       asha
5       geet
6       amar
7      amita
8       amol
9      anmol
Name: name, dtype: object

In [82]:
df['name']

0       anil
1       amit
2     aniket
3    ajinkya
4       asha
5       geet
6       amar
7      amita
8       amol
9      anmol
Name: name, dtype: object

In [84]:
df[['name','class']]

      name class
0     anil    TE
1     amit    TE
2   aniket    BE
3  ajinkya    TE
4     asha    TE
5     geet    BE
6     amar    BE
7    amita    BE
8     amol    TE
9    anmol    BE

In [85]:
# Methods on column&rows

In [90]:
df['name'].str.upper()

0       ANIL
1       AMIT
2     ANIKET
3    AJINKYA
4       ASHA
5       GEET
6       AMAR
7      AMITA
8       AMOL
9      ANMOL
Name: name, dtype: object

In [95]:
df['name'].str.startswith('a')

0     True
1     True
2     True
3     True
4     True
5    False
6     True
7     True
8     True
9     True
Name: name, dtype: bool

In [94]:
df['name'].str.endswith('l')

0     True
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8     True
9     True
Name: name, dtype: bool

In [96]:
dir(str)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',
 'zfill']

In [97]:
df['name'].str.isupper()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
Name: name, dtype: bool

In [98]:
df['name'].str.islower()

0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
8    True
9    True
Name: name, dtype: bool

In [99]:
df.name

0       anil
1       amit
2     aniket
3    ajinkya
4       asha
5       geet
6       amar
7      amita
8       amol
9      anmol
Name: name, dtype: object

# Add Column

In [103]:
gender=['m','m','m','m','f','m','m','f','m','m']

In [104]:
df['gender']= gender

In [105]:
df

   roll     name class  marks  age gender
0     1     anil    TE  56.77   22      m
1     2     amit    TE  59.77   21      m
2     3   aniket    BE  76.88   19      m
3     4  ajinkya    TE  69.66   20      m
4     5     asha    TE  63.28   20      f
5     6     geet    BE  49.55   20      m
6     7     amar    BE  65.34   19      m
7     8    amita    BE  68.33   23      f
8     9     amol    TE  56.75   20      m
9    10    anmol    BE  78.66   21      m

# Modified column

In [108]:
df['roll']=df['roll']+100
df

   roll     name class  marks  age gender
0   201     anil    TE  56.77   22      m
1   202     amit    TE  59.77   21      m
2   203   aniket    BE  76.88   19      m
3   204  ajinkya    TE  69.66   20      m
4   205     asha    TE  63.28   20      f
5   206     geet    BE  49.55   20      m
6   207     amar    BE  65.34   19      m
7   208    amita    BE  68.33   23      f
8   209     amol    TE  56.75   20      m
9   210    anmol    BE  78.66   21      m

In [109]:
# aadd new column cgpa
# values should => marks/10+1.5

In [110]:
df["cgpa"] = df["marks"] / 10 + 1.5

In [111]:
df

   roll     name class  marks  age gender   cgpa
0   201     anil    TE  56.77   22      m  7.177
1   202     amit    TE  59.77   21      m  7.477
2   203   aniket    BE  76.88   19      m  9.188
3   204  ajinkya    TE  69.66   20      m  8.466
4   205     asha    TE  63.28   20      f  7.828
5   206     geet    BE  49.55   20      m  6.455
6   207     amar    BE  65.34   19      m  8.034
7   208    amita    BE  68.33   23      f  8.333
8   209     amol    TE  56.75   20      m  7.175
9   210    anmol    BE  78.66   21      m  9.366

# Sorting By Values

In [115]:
df.sort_values(by='name')

   roll     name class  marks  age gender   cgpa
3   204  ajinkya    TE  69.66   20      m  8.466
6   207     amar    BE  65.34   19      m  8.034
1   202     amit    TE  59.77   21      m  7.477
7   208    amita    BE  68.33   23      f  8.333
8   209     amol    TE  56.75   20      m  7.175
2   203   aniket    BE  76.88   19      m  9.188
0   201     anil    TE  56.77   22      m  7.177
9   210    anmol    BE  78.66   21      m  9.366
4   205     asha    TE  63.28   20      f  7.828
5   206     geet    BE  49.55   20      m  6.455

In [116]:
# sort by class and then marks simultaneouslyand check the result

In [117]:
df.sort_values(by=['class','marks'])

   roll     name class  marks  age gender   cgpa
5   206     geet    BE  49.55   20      m  6.455
6   207     amar    BE  65.34   19      m  8.034
7   208    amita    BE  68.33   23      f  8.333
2   203   aniket    BE  76.88   19      m  9.188
9   210    anmol    BE  78.66   21      m  9.366
8   209     amol    TE  56.75   20      m  7.175
0   201     anil    TE  56.77   22      m  7.177
1   202     amit    TE  59.77   21      m  7.477
4   205     asha    TE  63.28   20      f  7.828
3   204  ajinkya    TE  69.66   20      m  8.466

In [119]:
df['marks'].mean()

np.float64(64.499)

In [120]:
df['marks'].max()

78.66

In [121]:
df.describe()

            roll      marks        age       cgpa
count   10.00000  10.000000  10.000000  10.000000
mean   205.50000  64.499000  20.500000   7.949900
std      3.02765   9.207179   1.269296   0.920718
min    201.00000  49.550000  19.000000   6.455000
25%    203.25000  57.520000  20.000000   7.252000
50%    205.50000  64.310000  20.000000   7.931000
75%    207.75000  69.327500  21.000000   8.432750
max    210.00000  78.660000  23.000000   9.366000

In [136]:
#groupby is use to grou the same category thing togethere

In [148]:
gr=df.groupby('class')

In [149]:
gr.groups

{'BE': [2, 5, 6, 7, 9], 'TE': [0, 1, 3, 4, 8]}

In [150]:
gr.get_group('BE')

   roll    name class  marks  age gender   cgpa
2   203  aniket    BE  76.88   19      m  9.188
5   206    geet    BE  49.55   20      m  6.455
6   207    amar    BE  65.34   19      m  8.034
7   208   amita    BE  68.33   23      f  8.333
9   210   anmol    BE  78.66   21      m  9.366

In [151]:
gr.get_group('TE')

   roll     name class  marks  age gender   cgpa
0   201     anil    TE  56.77   22      m  7.177
1   202     amit    TE  59.77   21      m  7.477
3   204  ajinkya    TE  69.66   20      m  8.466
4   205     asha    TE  63.28   20      f  7.828
8   209     amol    TE  56.75   20      m  7.175

In [153]:
gt=df.groupby('gender')

In [154]:
gt.groups

{'f': [4, 7], 'm': [0, 1, 2, 3, 5, 6, 8, 9]}

In [155]:
gt.get_group('m')

   roll     name class  marks  age gender   cgpa
0   201     anil    TE  56.77   22      m  7.177
1   202     amit    TE  59.77   21      m  7.477
2   203   aniket    BE  76.88   19      m  9.188
3   204  ajinkya    TE  69.66   20      m  8.466
5   206     geet    BE  49.55   20      m  6.455
6   207     amar    BE  65.34   19      m  8.034
8   209     amol    TE  56.75   20      m  7.175
9   210    anmol    BE  78.66   21      m  9.366

In [156]:
gt.get_group('f')

   roll   name class  marks  age gender   cgpa
4   205   asha    TE  63.28   20      f  7.828
7   208  amita    BE  68.33   23      f  8.333

In [157]:
gr.min()

       roll     name  marks  age gender   cgpa
class
BE      203     amar  49.55   19      f  6.455
TE      201  ajinkya  56.75   20      f  7.175

In [158]:
gr['marks'].mean()

class
BE    67.752
TE    61.246
Name: marks, dtype: float64

# Boolean filtering

In [161]:
df

   roll     name class  marks  age gender   cgpa
0   201     anil    TE  56.77   22      m  7.177
1   202     amit    TE  59.77   21      m  7.477
2   203   aniket    BE  76.88   19      m  9.188
3   204  ajinkya    TE  69.66   20      m  8.466
4   205     asha    TE  63.28   20      f  7.828
5   206     geet    BE  49.55   20      m  6.455
6   207     amar    BE  65.34   19      m  8.034
7   208    amita    BE  68.33   23      f  8.333
8   209     amol    TE  56.75   20      m  7.175
9   210    anmol    BE  78.66   21      m  9.366

In [160]:
df['marks']>60

0    False
1    False
2     True
3     True
4     True
5    False
6     True
7     True
8    False
9     True
Name: marks, dtype: bool

In [162]:
df[df['marks']>60]

   roll     name class  marks  age gender   cgpa
2   203   aniket    BE  76.88   19      m  9.188
3   204  ajinkya    TE  69.66   20      m  8.466
4   205     asha    TE  63.28   20      f  7.828
6   207     amar    BE  65.34   19      m  8.034
7   208    amita    BE  68.33   23      f  8.333
9   210    anmol    BE  78.66   21      m  9.366

In [163]:
# filter the data of those student->marks>60 and belong to be class

In [168]:
f = df[(df['marks'] > 60) & (df['class'] == 'BE')]    
f

   roll    name class  marks  age gender   cgpa
2   203  aniket    BE  76.88   19      m  9.188
6   207    amar    BE  65.34   19      m  8.034
7   208   amita    BE  68.33   23      f  8.333
9   210   anmol    BE  78.66   21      m  9.366

# Drops Rows and Column

In [169]:
df.drop(4)

   roll     name class  marks  age gender   cgpa
0   201     anil    TE  56.77   22      m  7.177
1   202     amit    TE  59.77   21      m  7.477
2   203   aniket    BE  76.88   19      m  9.188
3   204  ajinkya    TE  69.66   20      m  8.466
5   206     geet    BE  49.55   20      m  6.455
6   207     amar    BE  65.34   19      m  8.034
7   208    amita    BE  68.33   23      f  8.333
8   209     amol    TE  56.75   20      m  7.175
9   210    anmol    BE  78.66   21      m  9.366

In [171]:
df.drop([4,5,6])

   roll     name class  marks  age gender   cgpa
0   201     anil    TE  56.77   22      m  7.177
1   202     amit    TE  59.77   21      m  7.477
2   203   aniket    BE  76.88   19      m  9.188
3   204  ajinkya    TE  69.66   20      m  8.466
7   208    amita    BE  68.33   23      f  8.333
8   209     amol    TE  56.75   20      m  7.175
9   210    anmol    BE  78.66   21      m  9.366

In [180]:
#drop name column

In [179]:
df.drop(columns=['name'])

   roll class  marks  age gender   cgpa
0   201    TE  56.77   22      m  7.177
1   202    TE  59.77   21      m  7.477
2   203    BE  76.88   19      m  9.188
3   204    TE  69.66   20      m  8.466
4   205    TE  63.28   20      f  7.828
5   206    BE  49.55   20      m  6.455
6   207    BE  65.34   19      m  8.034
7   208    BE  68.33   23      f  8.333
8   209    TE  56.75   20      m  7.175
9   210    BE  78.66   21      m  9.366

In [181]:
df.drop('name',axis=1)

   roll class  marks  age gender   cgpa
0   201    TE  56.77   22      m  7.177
1   202    TE  59.77   21      m  7.477
2   203    BE  76.88   19      m  9.188
3   204    TE  69.66   20      m  8.466
4   205    TE  63.28   20      f  7.828
5   206    BE  49.55   20      m  6.455
6   207    BE  65.34   19      m  8.034
7   208    BE  68.33   23      f  8.333
8   209    TE  56.75   20      m  7.175
9   210    BE  78.66   21      m  9.366

In [183]:
df.drop (['name','class'],axis=1)

   roll  marks  age gender   cgpa
0   201  56.77   22      m  7.177
1   202  59.77   21      m  7.477
2   203  76.88   19      m  9.188
3   204  69.66   20      m  8.466
4   205  63.28   20      f  7.828
5   206  49.55   20      m  6.455
6   207  65.34   19      m  8.034
7   208  68.33   23      f  8.333
8   209  56.75   20      m  7.175
9   210  78.66   21      m  9.366

# To make chnages in permanent table we have  to use inplace=True

In [184]:
df.drop (['gender','cgpa'],axis=1,inplace=True)

In [185]:
df

   roll     name class  marks  age
0   201     anil    TE  56.77   22
1   202     amit    TE  59.77   21
2   203   aniket    BE  76.88   19
3   204  ajinkya    TE  69.66   20
4   205     asha    TE  63.28   20
5   206     geet    BE  49.55   20
6   207     amar    BE  65.34   19
7   208    amita    BE  68.33   23
8   209     amol    TE  56.75   20
9   210    anmol    BE  78.66   21

In [187]:
# create a dataframe
# columns->roll,gender,cgpa
#roll column will have same values as that of in the df dataframe

In [198]:
import pandas as pd

df2 = pd.DataFrame({
    'roll': df['roll'],
    'gender': ['M', 'F', 'M', 'F', 'M','M', 'F', 'M', 'F', 'M'], 
    'cgpa': [8.2, 9.1, 7.8, 8.9, 8.5,8.2, 9.1, 7.8, 8.9, 8.0]    
})

In [200]:
df2

   roll gender  cgpa
0   201      M   8.2
1   202      F   9.1
2   203      M   7.8
3   204      F   8.9
4   205      M   8.5
5   206      M   8.2
6   207      F   9.1
7   208      M   7.8
8   209      F   8.9
9   210      M   8.0

In [201]:

df2 = pd.DataFrame({
    'roll': df['roll'],
    'gender': gender, 
    'cgpa': df['marks']/10+1.5   
})

In [202]:
df2

   roll gender   cgpa
0   201      m  7.177
1   202      m  7.477
2   203      m  9.188
3   204      m  8.466
4   205      f  7.828
5   206      m  6.455
6   207      m  8.034
7   208      f  8.333
8   209      m  7.175
9   210      m  9.366

In [206]:
df2

   roll gender   cgpa
0   201      m  7.177
1   202      m  7.477
2   203      m  9.188
3   204      m  8.466
4   205      f  7.828
5   206      m  6.455
6   207      m  8.034
7   208      f  8.333
8   209      m  7.175
9   210      m  9.366

In [207]:
pd.merge(df,df2)

   roll     name class  marks  age gender   cgpa
0   201     anil    TE  56.77   22      m  7.177
1   202     amit    TE  59.77   21      m  7.477
2   203   aniket    BE  76.88   19      m  9.188
3   204  ajinkya    TE  69.66   20      m  8.466
4   205     asha    TE  63.28   20      f  7.828
5   206     geet    BE  49.55   20      m  6.455
6   207     amar    BE  65.34   19      m  8.034
7   208    amita    BE  68.33   23      f  8.333
8   209     amol    TE  56.75   20      m  7.175
9   210    anmol    BE  78.66   21      m  9.366

In [208]:
#cocat

In [209]:
#load student5.csv

In [226]:
df2

   roll gender   cgpa
0   201      m  7.177
1   202      m  7.477
2   203      m  9.188
3   204      m  8.466
4   205      f  7.828
5   206      m  6.455
6   207      m  8.034
7   208      f  8.333
8   209      m  7.175
9   210      m  9.366

In [224]:
df1=pd.read_csv('student5.csv')
df

   roll     name class  marks  age
0     1   surbhi    TE  67.44   23
1     2    sujay    TE  74.12   22
2     3  subhash    BE  82.44   21
3     4   sachin    TE  59.33   21
4     5  shalini    TE  63.45   20

In [232]:
pd.concat([df1 ,df2], ignore_index= True)

    roll     name class  marks   age gender   cgpa
0      1   surbhi    TE  67.44  23.0    NaN    NaN
1      2    sujay    TE  74.12  22.0    NaN    NaN
2      3  subhash    BE  82.44  21.0    NaN    NaN
3      4   sachin    TE  59.33  21.0    NaN    NaN
4      5  shalini    TE  63.45  20.0    NaN    NaN
5    201      NaN   NaN    NaN   NaN      m  7.177
6    202      NaN   NaN    NaN   NaN      m  7.477
7    203      NaN   NaN    NaN   NaN      m  9.188
8    204      NaN   NaN    NaN   NaN      m  8.466
9    205      NaN   NaN    NaN   NaN      f  7.828
10   206      NaN   NaN    NaN   NaN      m  6.455
11   207      NaN   NaN    NaN   NaN      m  8.034
12   208      NaN   NaN    NaN   NaN      f  8.333
13   209      NaN   NaN    NaN   NaN      m  7.175
14   210      NaN   NaN    NaN   NaN      m  9.366

In [229]:
f = df[(df['marks'] > 60) & (df['class'] == 'BE')]

In [230]:
f.to_csv('op_csv',index= False)